### PR TITLE
Added more improvements about i18n

### PR DESCRIPTION
**Pull request by macagua**
@ebrehault @djay may can check this improvements and if all are rigths, you can merge it?

- Updated Spanish translation [macagua]
- Added support for plomino.tinymce domain [macagua]
- Added more improvements about i18n [macagua]

### CODE REVIEW

**Review by ebrehault — CHANGES_REQUESTED** [review]
Looks good to me, but the test are broken because of the Plone version (trying to get Plone-5.0.10-UnifiedInstaller, which does not exist)

**Comment by macagua** [comment]
@ebrehault fixed the error for the Plone-5.0.10-UnifiedInstaller ;-)

**Review by ebrehault — CHANGES_REQUESTED** [review]
One of the test is broken, I guess that's a small change you made in markup.
Just copy/paste the new expected markup in the test and it should be fine.

**Comment by macagua** [comment]
@ebrehault ok I try with this!

**Comment by macagua** [comment]
@ebrehault done the fix about the functional test.

**Review by ebrehault — APPROVED** [review]

**Comment by ebrehault** [comment]
Thanks :)

**Comment by macagua** [comment]
@ebrehault no problems ;-)

**Pull request merged**
